language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: plY799kfeal8CNHsiP8A2N4VrRQ9Jk2+h0YfNYsbM0225UU/w7bh57uRBlRiXH+aX0HGHd6k2G2gsp6ngTUZt4yimOak16TUc5hsUK15ZRG/6Ntn0zQQ3lHGYEi2Ot9mEw5DV92D0MoztRWQSelA7OHNp1q8rPsxXEfmPqKnE8XJrYENoU1sAool//XMkFeTzSUAEiDAIgBrY5g8ljiBjpGRbK9HFOMzDnLz8flb4hVOqZtLwjNgOBxfiSgGQLW9u8rST0SCr9muvbP44JHSFuV52b8b3xVUgbtyLX10K2DlzTycrgM11cvLRzke2ufE6AfHdFsdf9fKmpyzHdk2+hWra9BzUZJVeIedKFKiRmpCSVawaT2j/QZBGYxrjdnmavy+5/OCNzPZnXZtM+jg42HIeE9FU1iKc+bVriXVARAL+L7uFBZGcrhe8J4tFpcIcGMrq0naE9ZHHB53yMTDA+mkAESicVq7Efu5KyMztjD98A220r1Mvf0CyJchWIhcU20zjykys5Q1nXbNoi/CoaW2KsG9riSDFxUsGyFNXK2KhgcY2+R0jxih4qrJnqIPOBicOywlf1Iqtc0BS+0IoliM288pZoJhBVIOXVTFcQBsKloBfzLxPaljCiduazcFP5+MVoGFYuugac592u+CednQj4WB1WimiFDUJRZrtQ4=
  on:
    tags: true
    repo: mrossi93/geometric_calibration
    python: 3.8
